spring.application.name=easypark-backend

spring.datasource.url=jdbc:mysql://localhost:3306/easypark?useSSL=false&serverTimezone=Asia/Jerusalem
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.address=0.0.0.0
server.port=8080

# JWT configuration
security.jwt.secret=trhtknzwhcucxehvfhdcrctr.nxhvajeifsurfkvfhyuccvhxyurhv
security.jwt.expiration-minutes=60


google.client-id=489117864776-2n3budaeu2s75q3dg8s6gb4088crampj.apps.googleusercontent.com

# SendGrid email configuration
sendgrid.api-key=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
mail.from=ameenkassem111@gmail.com

# front end URL for password reset link
app.frontend.reset-password-url=http://localhost:5173/reset-password
app.security.reset-token-expiration-minutes=30